using System.Runtime.InteropServices;
using Microsoft.Office.Interop.Excel;
using Excel = Microsoft.Office.Interop.Excel;
using ExcelAPI.Models;
using Microsoft.Extensions.Logging;

namespace ExcelAPI.Services
{
    /// <summary>
    /// Reads an Output Excel workbook (.xlsx) generated by WorkbookGenerator and
    /// reconstructs the original FormDefinition, including:
    ///   - Workbook structure (sheets, names, page setup, print area)
    ///   - _Fields hidden sheet (field metadata)
    ///   - Cell comments (field metadata fallback)
    ///   - Merged cells, row heights, column widths
    ///   - Cell styles (font, color, alignment, fill)
    ///   - Cell values (existing user-entered values)
    ///
    /// This enables the round-trip workflow:
    ///   Generate → Upload → Reconstruct → Edit → Regenerate
    /// </summary>
    public class WorkbookReaderService
    {
        private readonly ILogger<WorkbookReaderService> _logger;

        public WorkbookReaderService(ILogger<WorkbookReaderService> logger)
        {
            _logger = logger;
        }

        /// <summary>
        /// Read an Output Excel workbook and reconstruct the FormDefinition.
        /// </summary>
        /// <param name="filePath">Path to the .xlsx file.</param>
        /// <param name="fileName">Original file name (for metadata).</param>
        /// <returns>Reconstructed FormDefinition, or null if the workbook cannot be read.</returns>
        public FormDefinition? Read(string filePath, string fileName)
        {
            Application? excelApp = null;
            Workbook? workbook = null;

            try
            {
                excelApp = new Application
                {
                    Visible = false,
                    DisplayAlerts = false
                };

                workbook = excelApp.Workbooks.Open(filePath);

                var form = new FormDefinition
                {
                    Workbook = new WorkbookMetadata
                    {
                        Title = Path.GetFileNameWithoutExtension(fileName),
                        Author = "",
                        Created = DateTime.Now.ToString("o"),
                        Modified = DateTime.Now.ToString("o"),
                        Version = "1.0",
                        Description = $"Read from {fileName}"
                    },
                    Metadata = new Dictionary<string, string>
                    {
                        ["sourceFile"] = fileName,
                        ["capturedAt"] = DateTime.Now.ToString("o")
                    }
                };

                // Step 1: Read all worksheets
                int sheetCount = workbook.Worksheets.Count;
                _logger.LogInformation("Reading workbook '{File}': {Count} sheet(s)", fileName, sheetCount);

                // Build a map of sheet name → COM worksheet for content sheets (skip _Fields)
                var contentSheets = new List<(int index, Excel.Worksheet ws)>();
                Excel.Worksheet? fieldsSheet = null;

                for (int i = 1; i <= sheetCount; i++)
                {
                    var ws = (Excel.Worksheet)workbook.Worksheets[i];
                    string name = ws.Name;

                    if (string.Equals(name, "_Fields", StringComparison.OrdinalIgnoreCase))
                    {
                        fieldsSheet = ws;
                        _logger.LogInformation("Found _Fields hidden sheet");
                    }
                    else
                    {
                        contentSheets.Add((i, ws));
                    }
                }

                if (contentSheets.Count == 0)
                {
                    _logger.LogError("No content sheets found in workbook (only _Fields present)");
                    return null;
                }

                // Step 2: Read _Fields sheet (primary metadata source)
                var clustersFromFields = fieldsSheet != null
                    ? ReadFieldsSheet(fieldsSheet)
                    : new List<(string address, string fieldId, string fieldName, string fieldType, string sheetName)>();

                _logger.LogInformation("Read {Count} field definitions from _Fields sheet", clustersFromFields.Count);

                // Step 3: Read cell comments from each content sheet (fallback metadata)
                var commentsBySheet = new Dictionary<string, List<(string address, string text)>>();
                for (int si = 0; si < contentSheets.Count; si++)
                {
                    var (index, ws) = contentSheets[si];
                    var comments = ReadComments(ws);
                    if (comments.Count > 0)
                    {
                        commentsBySheet[ws.Name] = comments;
                        _logger.LogInformation("Sheet '{Name}': {Count} comment(s)", ws.Name, comments.Count);
                    }
                }

                // Step 4: Build SheetDefinitions for each content sheet
                int sheetIdx = 0;
                foreach (var (comIndex, ws) in contentSheets)
                {
                    string sheetName = ws.Name;
                    string sheetId = $"sheet_{sheetIdx}";

                    _logger.LogInformation("Processing sheet '{Name}' (id={Id})", sheetName, sheetId);

                    var sheetDef = new SheetDefinition
                    {
                        Id = sheetId,
                        Name = sheetName,
                        Index = sheetIdx,
                        PageSettings = ReadPageSettings(ws),
                        PrintArea = ReadPrintArea(ws),
                        FreezePane = ReadFreezePane(ws),
                        RowHeights = ReadRowHeights(ws),
                        ColumnWidths = ReadColumnWidths(ws),
                        MergedCells = ReadMergedCells(ws),
                        CellStyles = ReadCellStyles(ws),
                        CellValues = ReadCellValues(ws, clustersFromFields, commentsBySheet.GetValueOrDefault(sheetName))
                    };

                    form.Sheets.Add(sheetDef);
                    sheetIdx++;
                }

                // Step 4b: Capture cell styles from _Fields sheet for each field address
                // These styles supplement the content-sheet styles captured above,
                // ensuring single-cell fields (like "A12") and non-commented cells
                // are not missed even though ReadCellStyles only captures merged/commented cells.
                if (fieldsSheet != null && clustersFromFields.Count > 0)
                {
                    int capturedFromFields = 0;
                    foreach (var (addr, _, _, _, sheetName) in clustersFromFields)
                    {
                        string cellAddr = addr.Split(':')[0];
                        if (string.IsNullOrWhiteSpace(cellAddr)) continue;

                        // Find the target SheetDefinition for this cluster
                        var targetSheet = form.Sheets.FirstOrDefault(s =>
                            string.Equals(s.Name, sheetName, StringComparison.OrdinalIgnoreCase));
                        if (targetSheet == null) continue;

                        // Only add if not already captured from content sheet
                        if (targetSheet.CellStyles.ContainsKey(cellAddr)) continue;

                        try
                        {
                            var range = fieldsSheet.Range[cellAddr];
                            var style = ReadStyleFromRange(range);
                            targetSheet.CellStyles[cellAddr] = style;
                            Marshal.ReleaseComObject(range);
                            capturedFromFields++;
                            _logger.LogInformation("Captured style for {Cell} from _Fields sheet", cellAddr);
                        }
                        catch (Exception ex)
                        {
                            _logger.LogWarning(ex, "Failed to capture style for {Cell} from _Fields sheet", cellAddr);
                        }
                    }
                    _logger.LogInformation("Captured {Count} cell style(s) from _Fields sheet", capturedFromFields);
                }

                // Step 5: Build ClusterDefinitions from _Fields sheet (primary) or comments (fallback)
                int clusterIdx = 0;

                if (clustersFromFields.Count > 0)
                {
                    // Primary: Build from _Fields sheet data
                    // Log per-field trace in consolidated format for easy diagnosis
                    foreach (var entry in clustersFromFields)
                    {
                        var (address, fieldId, fieldName, fieldType, sheetName) = entry;

                        var cluster = BuildClusterFromDefinition(
                            form, address, fieldId, fieldName, fieldType, sheetName,
                            commentsBySheet, clusterIdx);

                        string hasComment = "NO";
                        string source = "_FIELDS";
                        string result = "CREATED";

                        if (cluster != null)
                        {
                            form.Clusters.Add(cluster);
                            // Check if we found a matching comment for enrichment
                            if (commentsBySheet.Count > 0 &&
                                commentsBySheet.Values.Any(cList =>
                                    cList.Any(c =>
                                        string.Equals(c.address, address.Split(':')[0],
                                        StringComparison.OrdinalIgnoreCase))))
                            {
                                hasComment = "FOUND";
                            }
                            clusterIdx++;
                        }
                        else
                        {
                            result = "SKIPPED";
                        }

                        _logger.LogInformation(
                            "FIELD #{Idx}: Sheet={Sheet} Address={Addr} _Fields=FOUND Comment={Comment} Cluster={Result}",
                            clusterIdx - (result == "CREATED" ? 1 : 0),
                            sheetName, address, hasComment, result);
                    }
                }
                else
                {
                    // Fallback: Build clusters from cell comments (legacy ConMas format)
                    int totalComments = 0;
                    foreach (var kvp in commentsBySheet) totalComments += kvp.Value.Count;
                    _logger.LogInformation(
                        "_Fields=MISSING building {Count} cluster(s) from comments (fallback)", totalComments);

                    foreach (var kvp in commentsBySheet)
                    {
                        string sheetName = kvp.Key;
                        var targetSheet = form.Sheets.FirstOrDefault(s =>
                            string.Equals(s.Name, sheetName, StringComparison.OrdinalIgnoreCase));
                        string sid = targetSheet?.Id ?? "sheet_0";

                        foreach (var (addr, text) in kvp.Value)
                        {
                            string cellAddr = addr.Split(':')[0];
                            string fieldName = $"Field_{clusterIdx}";
                            string fieldType = "text";

                            if (string.IsNullOrWhiteSpace(text))
                            {
                                _logger.LogWarning(
                                    "COMMENT #{Idx}: Sheet={Sheet} Address={Addr} _Fields=MISSING Comment=EMPTY Cluster=SKIPPED",
                                    clusterIdx, sheetName, cellAddr);
                                continue;
                            }

                            // Parse legacy comment format: Name\nType\n\nParams
                            string[] lines = text.Split('\n', StringSplitOptions.RemoveEmptyEntries);
                            if (lines.Length >= 1) fieldName = lines[0].Trim();
                            if (lines.Length >= 2) fieldType = lines[1].Trim();

                            var cluster = new ClusterDefinition
                            {
                                ClusterId = $"field_{clusterIdx}",
                                Name = fieldName,
                                Type = fieldType.ToLower(),
                                SheetId = sid,
                                CellAddress = cellAddr,
                                InputParameters = ParseCommentText(text),
                                Visibility = "visible",
                                Readonly = false,
                                Remarks = text,
                                Functions = new List<string>(),
                                Metadata = new Dictionary<string, string>
                                {
                                    ["isMerged"] = addr.Contains(":") ? "true" : "false",
                                    ["mergeAddress"] = addr.Contains(":") ? addr : "",
                                    ["source"] = "comment"
                                }
                            };

                            if (targetSheet != null)
                            {
                                targetSheet.CellValues.TryGetValue(cellAddr, out var currentValue);
                                cluster.Metadata["currentValue"] = currentValue ?? "";
                            }

                            form.Clusters.Add(cluster);
                            _logger.LogInformation(
                                "COMMENT #{Idx}: Sheet={Sheet} Address={Addr} _Fields=MISSING Comment=FOUND Cluster=CREATED",
                                clusterIdx, sheetName, cellAddr);
                            clusterIdx++;
                        }
                    }
                }

                _logger.LogInformation(
                    "Workbook reconstruction complete: {SheetCount} sheet(s), {ClusterCount} cluster(s)",
                    form.Sheets.Count, form.Clusters.Count);

                return form;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to read workbook '{File}'", filePath);
                return null;
            }
            finally
            {
                if (workbook != null)
                {
                    try { workbook.Close(SaveChanges: false); } catch { }
                    Marshal.ReleaseComObject(workbook);
                }
                if (excelApp != null)
                {
                    try { excelApp.Quit(); } catch { }
                    Marshal.ReleaseComObject(excelApp);
                }
                GC.Collect();
                GC.WaitForPendingFinalizers();
            }
        }

        // ────────────────────────────────────────────────────────────────────────
        // _Fields Sheet Reader
        // ────────────────────────────────────────────────────────────────────────

        /// <summary>
        /// Read the hidden _Fields worksheet.
        /// Expected columns: Address, FieldId, FieldName, FieldType, SheetName, CreatedDate, Notes
        /// Row 1 = headers, Row 2+ = data.
        /// </summary>
        private List<(string address, string fieldId, string fieldName, string fieldType, string sheetName)>
            ReadFieldsSheet(Excel.Worksheet ws)
        {
            var result = new List<(string, string, string, string, string)>();

            try
            {
                // Find the last used row
                int lastRow = 0;
                try { lastRow = ws.UsedRange.Rows.Count; } catch { }

                _logger.LogInformation(
                    "_Fields sheet UsedRange: lastRow={Row}, need at least 2 rows (header + data)", lastRow);

                if (lastRow < 2) // Need at least header + 1 data row
                {
                    _logger.LogInformation(
                        "_Fields sheet has no data rows (lastRow={Row}) — will fall back to comments", lastRow);
                    return result;
                }

                for (int row = 2; row <= lastRow; row++)
                {
                    try
                    {
                        string address = GetCellString(ws.Cells[row, 1]);
                        string fieldId = GetCellString(ws.Cells[row, 2]);
                        string fieldName = GetCellString(ws.Cells[row, 3]);
                        string fieldType = GetCellString(ws.Cells[row, 4]);
                        string sheetName = GetCellString(ws.Cells[row, 5]);

                        if (string.IsNullOrWhiteSpace(address))
                            continue; // Skip empty rows

                        result.Add((address, fieldId, fieldName, fieldType, sheetName));
                    }
                    catch
                    {
                        // Skip rows that fail to read
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to read _Fields sheet content");
            }

            return result;
        }

        // ────────────────────────────────────────────────────────────────────────
        // Comments Reader
        // ────────────────────────────────────────────────────────────────────────

        /// <summary>
        /// Read all cell comments from a worksheet via COM.
        /// Returns a list of (cellAddress, commentText).
        /// </summary>
        private List<(string address, string text)> ReadComments(Excel.Worksheet ws)
        {
            var result = new List<(string, string)>();

            try
            {
                dynamic? comments = null;
                try { comments = ws.Comments; } catch { }

                if (comments == null) return result;

                int commentCount = 0;
                try { commentCount = comments.Count; } catch { }

                for (int ci = 0; ci < commentCount; ci++)
                {
                    try
                    {
                        dynamic comment = comments[ci + 1];
                        dynamic parent = comment.Parent;

                        string address = "";
                        try { address = parent.Address; } catch { }

                        string text = "";
                        try { text = comment.Text() ?? ""; } catch { }

                        if (!string.IsNullOrWhiteSpace(address))
                        {
                            result.Add((address, text.Trim()));
                        }
                    }
                    catch
                    {
                        // Skip individual comment read failures
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to read comments from sheet '{Name}'", ws.Name);
            }

            return result;
        }

        // ────────────────────────────────────────────────────────────────────────
        // Page Settings Reader
        // ────────────────────────────────────────────────────────────────────────

        private PageSettings ReadPageSettings(Excel.Worksheet ws)
        {
            var settings = new PageSettings();

            try
            {
                var ps = ws.PageSetup;

                settings.Orientation = ps.Orientation == XlPageOrientation.xlLandscape
                    ? "landscape" : "portrait";
                settings.LeftMargin = SafeGetDouble(() => ps.LeftMargin, 70);
                settings.TopMargin = SafeGetDouble(() => ps.TopMargin, 70);
                settings.RightMargin = SafeGetDouble(() => ps.RightMargin, 70);
                settings.BottomMargin = SafeGetDouble(() => ps.BottomMargin, 70);

                try { settings.CenterHorizontally = (bool)ps.CenterHorizontally; } catch { }
                try { settings.CenterVertically = (bool)ps.CenterVertically; } catch { }

                int zoom = 0;
                try { zoom = (int)ps.Zoom; } catch { }
                if (zoom > 0) settings.Zoom = zoom;
                else settings.Zoom = 100;

                int fitW = 0, fitH = 0;
                try { fitW = (int)ps.FitToPagesWide; } catch { }
                try { fitH = (int)ps.FitToPagesTall; } catch { }
                settings.FitToPagesWide = fitW;
                settings.FitToPagesTall = fitH;

                // Paper size
                int paperSize = 0;
                try { paperSize = (int)ps.PaperSize; } catch { }
                settings.PaperSize = paperSize switch
                {
                    1 => "Letter",
                    5 => "Legal",
                    9 => "A4",
                    _ => $"Custom({paperSize})"
                };
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to read page settings");
            }

            return settings;
        }

        // ────────────────────────────────────────────────────────────────────────
        // Print Area Reader
        // ────────────────────────────────────────────────────────────────────────

        private PrintAreaInfo? ReadPrintArea(Excel.Worksheet ws)
        {
            try
            {
                string printArea = "";
                try { printArea = ws.PageSetup.PrintArea ?? ""; } catch { }

                if (string.IsNullOrWhiteSpace(printArea))
                    return null;

                return new PrintAreaInfo
                {
                    Address = printArea,
                    Cols = 0,
                    Rows = 0
                };
            }
            catch
            {
                return null;
            }
        }

        // ────────────────────────────────────────────────────────────────────────
        // Freeze Pane Reader
        // ────────────────────────────────────────────────────────────────────────

        private string? ReadFreezePane(Excel.Worksheet ws)
        {
            try
            {
                ws.Activate();
                bool hasFreezePanes = false;
                try { hasFreezePanes = (bool)ws.Application.ActiveWindow.FreezePanes; } catch { }

                if (hasFreezePanes)
                {
                    int scrollRow = 0, scrollCol = 0;
                    try { scrollRow = (int)ws.Application.ActiveWindow.ScrollRow; } catch { }
                    try { scrollCol = (int)ws.Application.ActiveWindow.ScrollColumn; } catch { }

                    if (scrollRow > 1 || scrollCol > 1)
                    {
                        return GetColumnLetter(scrollCol) + scrollRow;
                    }
                }
            }
            catch { }

            return null;
        }

        // ────────────────────────────────────────────────────────────────────────
        // Row Heights Reader
        // ────────────────────────────────────────────────────────────────────────

        private Dictionary<int, double> ReadRowHeights(Excel.Worksheet ws)
        {
            var result = new Dictionary<int, double>();

            try
            {
                var usedRange = ws.UsedRange;
                int lastRow = 0;
                try { lastRow = usedRange.Rows.Count + usedRange.Row - 1; } catch { return result; }

                for (int r = 1; r <= lastRow; r++)
                {
                    try
                    {
                        var row = (Excel.Range)ws.Rows[r];
                        double height = (double)row.RowHeight;
                        result[r] = height;
                        Marshal.ReleaseComObject(row);
                    }
                    catch { }
                }
            }
            catch { }

            return result;
        }

        // ────────────────────────────────────────────────────────────────────────
        // Column Widths Reader
        // ────────────────────────────────────────────────────────────────────────

        private Dictionary<int, double> ReadColumnWidths(Excel.Worksheet ws)
        {
            var result = new Dictionary<int, double>();

            try
            {
                var usedRange = ws.UsedRange;
                int lastCol = 0;
                try { lastCol = usedRange.Columns.Count + usedRange.Column - 1; } catch { return result; }

                for (int c = 1; c <= lastCol; c++)
                {
                    try
                    {
                        var col = (Excel.Range)ws.Columns[c];
                        double width = (double)col.ColumnWidth;
                        result[c] = width;
                        Marshal.ReleaseComObject(col);
                    }
                    catch { }
                }
            }
            catch { }

            return result;
        }

        // ────────────────────────────────────────────────────────────────────────
        // Merged Cells Reader
        // ────────────────────────────────────────────────────────────────────────

        private List<MergedCellInfo> ReadMergedCells(Excel.Worksheet ws)
        {
            var result = new List<MergedCellInfo>();

            try
            {
                // Iterate through UsedRange cells and check each cell's MergeArea
                // This avoids relying on Worksheet.MergeAreas which may not be exposed
                var usedRange = ws.UsedRange;
                if (usedRange == null) return result;

                int lastRow = usedRange.Row + usedRange.Rows.Count - 1;
                int lastCol = usedRange.Column + usedRange.Columns.Count - 1;

                Marshal.ReleaseComObject(usedRange);

                var visited = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

                int maxRow = Math.Min(lastRow, 500);
                int maxCol = Math.Min(lastCol, 100);

                for (int r = 1; r <= maxRow; r++)
                {
                    for (int c = 1; c <= maxCol; c++)
                    {
                        try
                        {
                            var cell = ws.Cells[r, c];
                            bool isMerged = false;
                            try { isMerged = (bool)cell.MergeCells; } catch { }

                            if (isMerged)
                            {
                                dynamic mergeArea = cell.MergeArea;
                                string address = "";
                                try { address = mergeArea.Address; } catch { }

                                if (!string.IsNullOrEmpty(address) && !visited.Contains(address))
                                {
                                    visited.Add(address);
                                    result.Add(new MergedCellInfo
                                    {
                                        Address = address,
                                        CellAddress = address.Split(':')[0]
                                    });
                                }
                            }

                            Marshal.ReleaseComObject(cell);
                        }
                        catch { }
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to read merged cells");
            }

            return result;
        }

        // ────────────────────────────────────────────────────────────────────────
        // Cell Styles Reader
        // ────────────────────────────────────────────────────────────────────────

        private Dictionary<string, CellStyleInfo> ReadCellStyles(Excel.Worksheet ws)
        {
            var result = new Dictionary<string, CellStyleInfo>();

            try
            {
                // Read styles from merged cells by iterating UsedRange and checking MergeCells
                var usedRange = ws.UsedRange;
                if (usedRange == null) return result;

                int lastRow = usedRange.Row + usedRange.Rows.Count - 1;
                int lastCol = usedRange.Column + usedRange.Columns.Count - 1;

                Marshal.ReleaseComObject(usedRange);

                var visitedAddrs = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

                int maxRow = Math.Min(lastRow, 500);
                int maxCol = Math.Min(lastCol, 100);

                for (int r = 1; r <= maxRow; r++)
                {
                    for (int c = 1; c <= maxCol; c++)
                    {
                        try
                        {
                            var cell = ws.Cells[r, c];
                            string cellAddr = "";

                            bool isMerged = false;
                            try { isMerged = (bool)cell.MergeCells; } catch { }

                            if (isMerged)
                            {
                                // For merged cells, use the top-left cell as the key
                                dynamic mergeArea = cell.MergeArea;
                                try { cellAddr = mergeArea.Address.Split(':')[0]; } catch { }
                            }
                            else
                            {
                                // For single cells, check if it has a comment (field indicator)
                                // cell.Comment returns a Comment object or null, not a bool
                                bool hasComment = false;
                                try { hasComment = cell.Comment != null; } catch { }
                                if (!hasComment) { Marshal.ReleaseComObject(cell); continue; }
                                try { cellAddr = cell.Address; } catch { }
                            }

                            if (!string.IsNullOrEmpty(cellAddr) && !visitedAddrs.Contains(cellAddr))
                            {
                                visitedAddrs.Add(cellAddr);
                                var range = ws.Range[cellAddr];
                                var style = ReadStyleFromRange(range);
                                result[cellAddr] = style;
                                Marshal.ReleaseComObject(range);
                            }

                            Marshal.ReleaseComObject(cell);
                        }
                        catch { }
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to read cell styles");
            }

            return result;
        }

        /// <summary>
        /// Read font, color, fill, alignment, and wrap from an Excel Range.
        /// </summary>
        private static CellStyleInfo ReadStyleFromRange(Excel.Range range)
        {
            var style = new CellStyleInfo();

            try { style.FontName = range.Font.Name; } catch { }
            try { style.FontSize = (double)range.Font.Size; } catch { }
            try { style.Bold = (bool)range.Font.Bold; } catch { }
            try { style.Italic = (bool)range.Font.Italic; } catch { }
            try { style.Underline = (bool)range.Font.Underline; } catch { }

            try
            {
                var fontColor = range.Font.Color;
                if (fontColor != null)
                {
                    int rgb = System.Convert.ToInt32(fontColor);
                    style.Color = $"#{rgb & 0xFFFFFF:X6}";
                }
            }
            catch { }

            try
            {
                var fillColor = range.Interior.Color;
                if (fillColor != null)
                {
                    int rgb = System.Convert.ToInt32(fillColor);
                    style.FillColor = $"#{rgb & 0xFFFFFF:X6}";
                }
            }
            catch { }

            try
            {
                int hAlign = (int)range.HorizontalAlignment;
                style.HorizontalAlignment = hAlign switch
                {
                    -4131 /* xlHAlignLeft */ => "left",
                    -4108 /* xlHAlignCenter */ => "center",
                    -4152 /* xlHAlignRight */ => "right",
                    _ => null
                };
            }
            catch { }

            try
            {
                int vAlign = (int)range.VerticalAlignment;
                style.VerticalAlignment = vAlign switch
                {
                    -4160 /* xlVAlignTop */ => "top",
                    -4108 /* xlVAlignCenter */ => "center",
                    -4107 /* xlVAlignBottom */ => "bottom",
                    _ => null
                };
            }
            catch { }

            try { style.WrapText = (bool)range.WrapText; } catch { }

            // Borders — capture individual edges from COM
            try { style.BorderLeft = ReadBorderCss(range, 7); } catch { }    // xlEdgeLeft
            try { style.BorderRight = ReadBorderCss(range, 10); } catch { }  // xlEdgeRight
            try { style.BorderTop = ReadBorderCss(range, 8); } catch { }     // xlEdgeTop
            try { style.BorderBottom = ReadBorderCss(range, 9); } catch { }  // xlEdgeBottom

            return style;
        }

        /// <summary>
        /// Read a single border edge from Excel COM and return CSS-style string
        /// like "1px solid #000000", or null if no border exists.
        /// </summary>
        private static string? ReadBorderCss(Excel.Range range, int edgeIndex)
        {
            try
            {
                var border = range.Borders[(XlBordersIndex)edgeIndex];
                object? lineStyleObj = null;
                try { lineStyleObj = border.LineStyle; } catch { }
                if (lineStyleObj == null) return null;

                int lineStyleVal = System.Convert.ToInt32(lineStyleObj);
                // xlLineStyleNone = -4142 means no border
                if (lineStyleVal == -4142) return null;

                string lineStyle = lineStyleVal switch
                {
                    -4115 => "dashed",   // xlDash
                    -4118 => "dotted",   // xlDot
                    -4119 => "double",   // xlDouble
                    _ => "solid"         // xlContinuous (-4142 already handled, but treat anything else as solid)
                };

                string width = "1px";
                try
                {
                    object? weightObj = border.Weight;
                    if (weightObj != null)
                    {
                        int wt = System.Convert.ToInt32(weightObj);
                        width = wt switch
                        {
                            -4138 => "2px", // xlMedium
                            4 => "3px",     // xlThick
                            _ => "1px"      // xlThin (2) or default
                        };
                    }
                }
                catch { }

                string colorStr = "#000000";
                try
                {
                    object? colorObj = border.Color;
                    if (colorObj != null)
                    {
                        int rgb = System.Convert.ToInt32(colorObj);
                        colorStr = $"#{rgb & 0xFFFFFF:X6}";
                    }
                }
                catch { }

                Marshal.ReleaseComObject(border);
                return $"{width} {lineStyle} {colorStr}";
            }
            catch
            {
                return null;
            }
        }

        // ────────────────────────────────────────────────────────────────────────
        // Cell Values Reader
        // ────────────────────────────────────────────────────────────────────────

        /// <summary>
        /// Read cell values from the worksheet for each field address.
        /// </summary>
        private Dictionary<string, string> ReadCellValues(
            Excel.Worksheet ws,
            List<(string address, string fieldId, string fieldName, string fieldType, string sheetName)> clustersFromFields,
            List<(string address, string text)>? comments)
        {
            var result = new Dictionary<string, string>();

            // Read values from _Fields addresses
            foreach (var (address, _, _, _, _) in clustersFromFields)
            {
                string cellAddr = address.Split(':')[0]; // Use first cell of merge range
                if (string.IsNullOrWhiteSpace(cellAddr)) continue;

                try
                {
                    var range = ws.Range[cellAddr];
                    object? value = null;
                    try { value = range.Value; } catch { }

                    if (value != null)
                    {
                        string strVal = value.ToString() ?? "";
                        if (!string.IsNullOrWhiteSpace(strVal))
                        {
                            result[cellAddr] = strVal;
                        }
                    }

                    Marshal.ReleaseComObject(range);
                }
                catch { }
            }

            // Also read values from comment addresses (fallback)
            if (comments != null)
            {
                foreach (var (addr, _) in comments)
                {
                    string cellAddr = addr.Split(':')[0];
                    if (result.ContainsKey(cellAddr)) continue;

                    try
                    {
                        var range = ws.Range[cellAddr];
                        object? value = null;
                        try { value = range.Value; } catch { }

                        if (value != null)
                        {
                            string strVal = value.ToString() ?? "";
                            if (!string.IsNullOrWhiteSpace(strVal))
                            {
                                result[cellAddr] = strVal;
                            }
                        }

                        Marshal.ReleaseComObject(range);
                    }
                    catch { }
                }
            }

            return result;
        }

        // ────────────────────────────────────────────────────────────────────────
        // Helpers
        // ────────────────────────────────────────────────────────────────────────

        private static string GetCellString(dynamic cell)
        {
            try
            {
                object? value = cell.Value;
                if (value == null) return "";
                return value.ToString()?.Trim() ?? "";
            }
            catch
            {
                return "";
            }
        }

        private static double SafeGetDouble(Func<object?> getter, double defaultValue)
        {
            try
            {
                object? val = getter();
                if (val == null) return defaultValue;
                return System.Convert.ToDouble(val);
            }
            catch
            {
                return defaultValue;
            }
        }

        /// <summary>
        /// Parse comment text in legacy ConMas format into InputParameters dictionary.
        /// Format: Name\nType\n\nParams or 0
        /// </summary>
        private static Dictionary<string, string> ParseCommentText(string text)
        {
            var result = new Dictionary<string, string>();
            if (string.IsNullOrWhiteSpace(text)) return result;

            string[] lines = text.Split('\n', StringSplitOptions.RemoveEmptyEntries);

            if (lines.Length >= 1)
                result["name"] = lines[0].Trim();
            if (lines.Length >= 2)
                result["type"] = lines[1].Trim();
            if (lines.Length >= 4)
            {
                string paramStr = lines[3].Trim();
                if (!string.IsNullOrEmpty(paramStr) && paramStr != "0")
                {
                    // Parse semicolon-delimited key=value pairs
                    foreach (var pair in paramStr.Split(';', StringSplitOptions.RemoveEmptyEntries))
                    {
                        int eqIdx = pair.IndexOf('=');
                        if (eqIdx > 0)
                        {
                            string key = pair[..eqIdx].Trim();
                            string val = pair[(eqIdx + 1)..].Trim();
                            if (!string.IsNullOrEmpty(key))
                                result[key] = val;
                        }
                    }
                }
            }

            return result;
        }

        /// <summary>
        /// Build a ClusterDefinition from _Fields sheet row data, enriched with comment metadata.
        /// </summary>
        private static ClusterDefinition? BuildClusterFromDefinition(
            FormDefinition form,
            string address, string fieldId, string fieldName, string fieldType, string sheetName,
            Dictionary<string, List<(string address, string text)>> commentsBySheet,
            int clusterIdx)
        {
            var targetSheet = form.Sheets.FirstOrDefault(s =>
                string.Equals(s.Name, sheetName, StringComparison.OrdinalIgnoreCase));
            string sid = targetSheet?.Id ?? "sheet_0";

            // Parse input parameters from comment text if available
            var inputParams = new Dictionary<string, string>();
            string commentText = "";

            if (targetSheet != null && commentsBySheet.TryGetValue(targetSheet.Name, out var sheetComments))
            {
                var cmt = sheetComments.FirstOrDefault(c =>
                    string.Equals(c.address, address.Split(':')[0], StringComparison.OrdinalIgnoreCase));
                if (cmt.text != "")
                {
                    commentText = cmt.text;
                    inputParams = ParseCommentText(cmt.text);
                }
            }

            var cluster = new ClusterDefinition
            {
                ClusterId = !string.IsNullOrEmpty(fieldId) ? fieldId : $"field_{clusterIdx}",
                Name = !string.IsNullOrEmpty(fieldName) ? fieldName : $"Field_{clusterIdx}",
                Type = !string.IsNullOrEmpty(fieldType) ? fieldType : "text",
                SheetId = sid,
                CellAddress = address,
                InputParameters = inputParams,
                Visibility = "visible",
                Readonly = false,
                Remarks = commentText,
                Functions = new List<string>(),
                Metadata = new Dictionary<string, string>
                {
                    ["isMerged"] = address.Contains(":") ? "true" : "false",
                    ["mergeAddress"] = address.Contains(":") ? address : "",
                    ["source"] = "_fields"
                }
            };

            // Read the current value from CellValues
            if (targetSheet != null)
            {
                targetSheet.CellValues.TryGetValue(address.Split(':')[0], out var currentValue);
                cluster.Metadata["currentValue"] = currentValue ?? "";
            }

            return cluster;
        }

        /// <summary>
        /// Convert a column number to a letter (1 = A, 2 = B, ... 27 = AA).
        /// </summary>
        private static string GetColumnLetter(int col)
        {
            string result = "";
            while (col > 0)
            {
                col--;
                result = (char)('A' + col % 26) + result;
                col /= 26;
            }
            return result;
        }
    }
}
