/**
 * Phase 28 — Overlay Coordinate Engine
 *
 * Defines the overlay types and models used by the PaperLess overlay engine.
 * Every Excel comment becomes an overlay definition with pixel-accurate coordinates.
 */

/** Supported overlay field types */
export type OverlayType =
  | "textbox"
  | "signature"
  | "checkbox"
  | "date"
  | "number"
  | "qr"
  | "barcode"
  | "image"
  | "ocr"
  | "unknown";

/**
 * An overlay definition — a single field region on the rendered Excel page.
 * Coordinates are in points (pt) measured from the print origin (top-left of content area).
 */
export interface OverlayModel {
  /** Unique identifier for this overlay (e.g., "field_A1", "img_0") */
  id: string;
  /** Overlay field type, inferred from the comment text or data source */
  type: OverlayType;
  /** Cell reference (e.g., "A5", "C3:D4" for merged cells) */
  cell: string;
  /** Distance from print origin left edge to overlay left edge, in points */
  leftPt: number;
  /** Distance from print origin top edge to overlay top edge, in points */
  topPt: number;
  /** Overlay width in points */
  widthPt: number;
  /** Overlay height in points */
  heightPt: number;
  /** Rotation in degrees (0 = no rotation) */
  rotation: number;
  /** Arbitrary metadata associated with this overlay */
  metadata: Record<string, unknown>;
}

/**
 * Collection of all overlays for a single template.
 * Generated by the OverlayEngine from the TemplateModel.
 */
export interface OverlayCollection {
  /** Template identifier */
  templateId: number;
  /** All overlays computed for this template */
  overlays: OverlayModel[];
  /** Overlays indexed by id for fast lookup */
  byId: Record<string, OverlayModel>;
  /** Overlays indexed by cell reference for fast lookup */
  byCell: Record<string, OverlayModel>;
  /** Timestamp of when these overlays were generated */
  generatedAt: string;
}
