using System.Runtime.InteropServices;
using Microsoft.Office.Interop.Excel;
using Excel = Microsoft.Office.Interop.Excel;
using ExcelAPI.Models;
using Microsoft.Extensions.Logging;
using DocumentFormat.OpenXml.Packaging;
using OpenXmlSpreadsheet = DocumentFormat.OpenXml.Spreadsheet;
using WbDef = ExcelAPI.Models.WorkbookDefinition;

namespace ExcelAPI.Designer.Analysis
{
    /// <summary>
    /// Reads an Output Excel workbook (.xlsx) generated by WorkbookGenerator and
    /// reconstructs the original FormDefinition, including:
    ///   - Workbook structure (sheets, names, page setup, print area)
    ///   - _Fields hidden sheet (field metadata)
    ///   - Cell comments (field metadata fallback)
    ///   - Merged cells, row heights, column widths
    ///   - Cell styles (font, color, alignment, fill)
    ///   - Cell values (existing user-entered values)
    ///
    /// This enables the round-trip workflow:
    ///   Generate → Upload → Reconstruct → Edit → Regenerate
    /// </summary>
    public class WorkbookReaderService
    {
        private readonly ILogger<WorkbookReaderService> _logger;

        public WorkbookReaderService(ILogger<WorkbookReaderService> logger)
        {
            _logger = logger;
        }

        /// <summary>
        /// Read an Output Excel workbook and reconstruct the FormDefinition.
        /// </summary>
        /// <param name="filePath">Path to the .xlsx file.</param>
        /// <param name="fileName">Original file name (for metadata).</param>
        /// <returns>Reconstructed FormDefinition, or null if the workbook cannot be read.</returns>
        public FormDefinition? Read(string filePath, string fileName)
        {
            // Step 0: Read _Fields PageSetup from OOXML BEFORE Excel COM opens the file.
            // COM returns Excel defaults for hidden sheets — the real values (custom
            // margins, centering) are only accessible from the OOXML package.
            // Reading before COM avoids file-lock conflicts.
            var fieldsPageSetup = ReadSheetPageSetupFromOoxml(filePath, "_Fields");

            App? excelApp = null;
            Workbook? workbook = null;

            try
            {
                excelApp = new App
                {
                    Visible = false,
                    DisplayAlerts = false
                };

                workbook = excelApp.Workbooks.Open(filePath);

                var form = new FormDefinition
                {
                    FieldsPageSettings = fieldsPageSetup,
                    Workbook = new WorkbookMetadata
                    {
                        Title = Path.GetFileNameWithoutExtension(fileName),
                        Author = "",
                        Created = DateTime.Now.ToString("o"),
                        Modified = DateTime.Now.ToString("o"),
                        Version = "1.0",
                        Description = $"Read from {fileName}"
                    },
                    Metadata = new Dictionary<string, string>
                    {
                        ["sourceFile"] = fileName,
                        ["capturedAt"] = DateTime.Now.ToString("o")
                    }
                };

                // Step 1: Read all worksheets
                int sheetCount = workbook.Worksheets.Count;
                _logger.LogInformation("Reading workbook '{File}': {Count} sheet(s)", fileName, sheetCount);

                // ═══ CP1: Log original PageSetup from COM immediately after open ═══
                _logger.LogInformation("[X28] ===== CP1: Original workbook COM PageSetup =====");
                for (int cpi = 1; cpi <= sheetCount; cpi++)
                {
                    var cpWs = (Excel.Worksheet)workbook.Worksheets[cpi];
                    LogPageSetup($"CP1-S{cpi}({cpWs.Name})", cpWs);
                    Marshal.ReleaseComObject(cpWs);
                }

                // Build a map of sheet name → COM worksheet for content sheets (skip _Fields)
                var contentSheets = new List<(int index, Excel.Worksheet ws)>();
                Excel.Worksheet? fieldsSheet = null;

                for (int i = 1; i <= sheetCount; i++)
                {
                    var ws = (Excel.Worksheet)workbook.Worksheets[i];
                    string name = ws.Name;

                    if (string.Equals(name, "_Fields", StringComparison.OrdinalIgnoreCase))
                    {
                        fieldsSheet = ws;
                        _logger.LogInformation("Found _Fields hidden sheet");
                    }
                    else
                    {
                        contentSheets.Add((i, ws));
                    }
                }

                if (contentSheets.Count == 0)
                {
                    _logger.LogError("No content sheets found in workbook (only _Fields present)");
                    return null;
                }

                // Step 2: Read _Fields sheet (primary metadata source)
                var clustersFromFields = fieldsSheet != null
                    ? ReadFieldsSheet(fieldsSheet)
                    : new List<(string address, string fieldId, string fieldName, string fieldType, string sheetName)>();

                _logger.LogInformation("Read {Count} field definitions from _Fields sheet", clustersFromFields.Count);

                // Step 3: Read cell comments from each content sheet (fallback metadata)
                var commentsBySheet = new Dictionary<string, List<(string address, string text)>>();
                for (int si = 0; si < contentSheets.Count; si++)
                {
                    var (index, ws) = contentSheets[si];
                    var comments = ReadComments(ws);
                    if (comments.Count > 0)
                    {
                        commentsBySheet[ws.Name] = comments;
                        _logger.LogInformation("Sheet '{Name}': {Count} comment(s)", ws.Name, comments.Count);
                    }
                }

                // Step 4: Build SheetDefinitions for each content sheet
                int sheetIdx = 0;
                foreach (var (comIndex, ws) in contentSheets)
                {
                    string sheetName = ws.Name;
                    string sheetId = $"sheet_{sheetIdx}";

                    _logger.LogInformation("Processing sheet '{Name}' (id={Id})", sheetName, sheetId);

                    var psCom = ReadPageSettings(ws);
                    var psOoxml = ReadSheetPageSetupFromOoxml(filePath, sheetName);
                    if (psOoxml != null)
                    {
                        // OOXML has exact margin/centering values — override COM
                        // which can have float precision issues (53.8583pt → 54pt).
                        // Only override if OOXML differs from COM by more than 0.01pt.
                        if (Math.Abs(psOoxml.LeftMargin - psCom.LeftMargin) > 0.01)
                            psCom.LeftMargin = psOoxml.LeftMargin;
                        if (Math.Abs(psOoxml.RightMargin - psCom.RightMargin) > 0.01)
                            psCom.RightMargin = psOoxml.RightMargin;
                        if (Math.Abs(psOoxml.TopMargin - psCom.TopMargin) > 0.01)
                            psCom.TopMargin = psOoxml.TopMargin;
                        if (Math.Abs(psOoxml.BottomMargin - psCom.BottomMargin) > 0.01)
                            psCom.BottomMargin = psOoxml.BottomMargin;
                        if (psOoxml.CenterHorizontally != psCom.CenterHorizontally)
                            psCom.CenterHorizontally = psOoxml.CenterHorizontally;
                        if (psOoxml.CenterVertically != psCom.CenterVertically)
                            psCom.CenterVertically = psOoxml.CenterVertically;
                        if (!string.Equals(psOoxml.Orientation, psCom.Orientation, StringComparison.OrdinalIgnoreCase))
                            psCom.Orientation = psOoxml.Orientation;
                    }

                    var sheetDef = new SheetDefinition
                    {
                        Id = sheetId,
                        Name = sheetName,
                        Index = sheetIdx,
                        PageSettings = psCom,
                        PrintArea = ReadPrintArea(ws),
                        FreezePane = ReadFreezePane(ws),
                        RowHeights = ReadRowHeights(ws),
                        ColumnWidths = ReadColumnWidths(ws),
                        MergedCells = ReadMergedCells(ws),
                        CellStyles = ReadCellStyles(ws),
                        CellValues = ReadCellValues(ws, clustersFromFields, commentsBySheet.GetValueOrDefault(sheetName))
                    };

                    form.Sheets.Add(sheetDef);
                    // ═══ CP2: Log model PageSettings values ═══
                    _logger.LogInformation(
                        "[X28] ===== CP2: Model PageSettings for sheet '{Name}' =====", sheetName);
                    _logger.LogInformation(
                        "[X28] [CP2-{Name}] MDL: CH={CH} CV={CV} LM={LM:F4} RM={RM:F4} TM={TM:F4} BM={BM:F4} O={O} Z={Z} FW={FW} FH={FH} PA={PA}",
                        sheetName,
                        psCom.CenterHorizontally, psCom.CenterVertically,
                        psCom.LeftMargin, psCom.RightMargin, psCom.TopMargin, psCom.BottomMargin,
                        psCom.Orientation ?? "(null)", psCom.Zoom, psCom.FitToPagesWide, psCom.FitToPagesTall,
                        sheetDef.PrintArea?.Address ?? "(none)");

                    sheetIdx++;
                }

                // Step 4b: Capture cell styles from _Fields sheet for each field address
                // These styles supplement the content-sheet styles captured above,
                // ensuring single-cell fields (like "A12") and non-commented cells
                // are not missed even though ReadCellStyles only captures merged/commented cells.
                if (fieldsSheet != null && clustersFromFields.Count > 0)
                {
                    int capturedFromFields = 0;
                    foreach (var (addr, _, _, _, sheetName) in clustersFromFields)
                    {
                        string cellAddr = addr.Split(':')[0];
                        if (string.IsNullOrWhiteSpace(cellAddr)) continue;

                        // Find the target SheetDefinition for this cluster
                        var targetSheet = form.Sheets.FirstOrDefault(s =>
                            string.Equals(s.Name, sheetName, StringComparison.OrdinalIgnoreCase));
                        if (targetSheet == null) continue;

                        // Only add if not already captured from content sheet
                        if (targetSheet.CellStyles.ContainsKey(cellAddr)) continue;

                        try
                        {
                            var range = fieldsSheet.Range[cellAddr];
                            var style = ReadStyleFromRange(range);
                            targetSheet.CellStyles[cellAddr] = style;
                            Marshal.ReleaseComObject(range);
                            capturedFromFields++;
                            _logger.LogInformation("Captured style for {Cell} from _Fields sheet", cellAddr);
                        }
                        catch (Exception ex)
                        {
                            _logger.LogWarning(ex, "Failed to capture style for {Cell} from _Fields sheet", cellAddr);
                        }
                    }
                    _logger.LogInformation("Captured {Count} cell style(s) from _Fields sheet", capturedFromFields);
                }

                // Step 4c: Read _Fields PageSetup from OOXML (not COM — hidden sheet
                // Step 4d: Ensure FieldsPageSettings is populated.
                // Primary source was already read from OOXML before COM open (Step 0).
                // Fall back to COM Interop if OOXML failed (returns Excel defaults for
                // hidden sheets, but is better than nothing for centering OR logic).
                if (form.FieldsPageSettings == null)
                {
                    if (fieldsSheet != null)
                    {
                        var fieldsCom = ReadPageSettings(fieldsSheet);
                        form.FieldsPageSettings = fieldsCom;
                        _logger.LogWarning("[PAGESETUP] OOXML _Fields read FAILED — falling back to COM _Fields values");
                    }
                    else
                    {
                        _logger.LogWarning("[PAGESETUP] Both OOXML and COM _Fields reads FAILED — no _Fields PageSetup available");
                    }
                }

                // Step 5: Build ClusterDefinitions from _Fields sheet (primary) or comments (fallback)
                int clusterIdx = 0;

                if (clustersFromFields.Count > 0)
                {
                    // Primary: Build from _Fields sheet data
                    // Log per-field trace in consolidated format for easy diagnosis
                    foreach (var entry in clustersFromFields)
                    {
                        var (address, fieldId, fieldName, fieldType, sheetName) = entry;

                        var cluster = BuildClusterFromDefinition(
                            form, address, fieldId, fieldName, fieldType, sheetName,
                            commentsBySheet, clusterIdx);

                        string hasComment = "NO";
                        string source = "_FIELDS";
                        string result = "CREATED";

                        if (cluster != null)
                        {
                            form.Clusters.Add(cluster);
                            // Check if we found a matching comment for enrichment
                            if (commentsBySheet.Count > 0 &&
                                commentsBySheet.Values.Any(cList =>
                                    cList.Any(c =>
                                        string.Equals(c.address, address.Split(':')[0],
                                        StringComparison.OrdinalIgnoreCase))))
                            {
                                hasComment = "FOUND";
                            }
                            clusterIdx++;
                        }
                        else
                        {
                            result = "SKIPPED";
                        }

                        _logger.LogInformation(
                            "FIELD #{Idx}: Sheet={Sheet} Address={Addr} _Fields=FOUND Comment={Comment} Cluster={Result}",
                            clusterIdx - (result == "CREATED" ? 1 : 0),
                            sheetName, address, hasComment, result);
                    }
                }
                else
                {
                    // Fallback: Build clusters from cell comments (legacy ConMas format)
                    int totalComments = 0;
                    foreach (var kvp in commentsBySheet) totalComments += kvp.Value.Count;
                    _logger.LogInformation(
                        "_Fields=MISSING building {Count} cluster(s) from comments (fallback)", totalComments);

                    foreach (var kvp in commentsBySheet)
                    {
                        string sheetName = kvp.Key;
                        var targetSheet = form.Sheets.FirstOrDefault(s =>
                            string.Equals(s.Name, sheetName, StringComparison.OrdinalIgnoreCase));
                        string sid = targetSheet?.Id ?? "sheet_0";

                        foreach (var (addr, text) in kvp.Value)
                        {
                            string cellAddr = addr.Split(':')[0];
                            string fieldName = $"Field_{clusterIdx}";
                            string fieldType = "text";

                            if (string.IsNullOrWhiteSpace(text))
                            {
                                _logger.LogWarning(
                                    "COMMENT #{Idx}: Sheet={Sheet} Address={Addr} _Fields=MISSING Comment=EMPTY Cluster=SKIPPED",
                                    clusterIdx, sheetName, cellAddr);
                                continue;
                            }

                            // Parse legacy comment format: Name\nType\n\nParams
                            string[] lines = text.Split('\n', StringSplitOptions.RemoveEmptyEntries);
                            if (lines.Length >= 1) fieldName = lines[0].Trim();
                            if (lines.Length >= 2) fieldType = lines[1].Trim();

                            var cluster = new ClusterDefinition
                            {
                                ClusterId = $"field_{clusterIdx}",
                                Name = fieldName,
                                Type = fieldType.ToLower(),
                                SheetId = sid,
                                CellAddress = cellAddr,
                                InputParameters = ParseCommentText(text),
                                Visibility = "visible",
                                Readonly = false,
                                Remarks = text,
                                Functions = new List<string>(),
                                Metadata = new Dictionary<string, string>
                                {
                                    ["isMerged"] = addr.Contains(":") ? "true" : "false",
                                    ["mergeAddress"] = addr.Contains(":") ? addr : "",
                                    ["source"] = "comment"
                                }
                            };

                            if (targetSheet != null)
                            {
                                targetSheet.CellValues.TryGetValue(cellAddr, out var currentValue);
                                cluster.Metadata["currentValue"] = currentValue ?? "";
                            }

                            form.Clusters.Add(cluster);
                            _logger.LogInformation(
                                "COMMENT #{Idx}: Sheet={Sheet} Address={Addr} _Fields=MISSING Comment=FOUND Cluster=CREATED",
                                clusterIdx, sheetName, cellAddr);
                            clusterIdx++;
                        }
                    }
                }

                _logger.LogInformation(
                    "Workbook reconstruction complete: {SheetCount} sheet(s), {ClusterCount} cluster(s)",
                    form.Sheets.Count, form.Clusters.Count);

                return form;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to read workbook '{File}'", filePath);
                return null;
            }
            finally
            {
                if (workbook != null)
                {
                    try { workbook.Close(SaveChanges: false); } catch { }
                    Marshal.ReleaseComObject(workbook);
                }
                if (excelApp != null)
                {
                    try { excelApp.Quit(); } catch { }
                    Marshal.ReleaseComObject(excelApp);
                }
                GC.Collect();
                GC.WaitForPendingFinalizers();
            }
        }

        // ────────────────────────────────────────────────────────────────────────
        // _Fields Sheet Reader
        // ────────────────────────────────────────────────────────────────────────

        /// <summary>
        /// Read the hidden _Fields worksheet.
        /// Expected columns: Address, FieldId, FieldName, FieldType, SheetName, CreatedDate, Notes
        /// Row 1 = headers, Row 2+ = data.
        /// </summary>
        private List<(string address, string fieldId, string fieldName, string fieldType, string sheetName)>
            ReadFieldsSheet(Excel.Worksheet ws)
        {
            var result = new List<(string, string, string, string, string)>();

            try
            {
                // Find the last used row
                int lastRow = 0;
                try { lastRow = ws.UsedRange.Rows.Count; } catch { }

                _logger.LogInformation(
                    "_Fields sheet UsedRange: lastRow={Row}, need at least 2 rows (header + data)", lastRow);

                if (lastRow < 2) // Need at least header + 1 data row
                {
                    _logger.LogInformation(
                        "_Fields sheet has no data rows (lastRow={Row}) — will fall back to comments", lastRow);
                    return result;
                }

                for (int row = 2; row <= lastRow; row++)
                {
                    try
                    {
                        string address = GetCellString(ws.Cells[row, 1]);
                        string fieldId = GetCellString(ws.Cells[row, 2]);
                        string fieldName = GetCellString(ws.Cells[row, 3]);
                        string fieldType = GetCellString(ws.Cells[row, 4]);
                        string sheetName = GetCellString(ws.Cells[row, 5]);

                        if (string.IsNullOrWhiteSpace(address))
                            continue; // Skip empty rows

                        result.Add((address, fieldId, fieldName, fieldType, sheetName));
                    }
                    catch
                    {
                        // Skip rows that fail to read
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to read _Fields sheet content");
            }

            return result;
        }

        // ────────────────────────────────────────────────────────────────────────
        // _Fields PageSetup OOXML Reader
        // ────────────────────────────────────────────────────────────────────────

        /// <summary>
        /// Read a worksheet's PageSetup directly from the OOXML package.
        /// COM Interop can have precision issues (e.g., 53.8583pt → 54pt) and
        /// hidden sheets return Excel defaults instead of real values.
        /// OOXML gives exact values stored in the file.
        ///
        /// OOXML stores margins in inches; we convert to points (×72).
        /// Centering is stored in PrintOptions, orientation in PageSetup.
        /// </summary>
        private PageSettings? ReadSheetPageSetupFromOoxml(string filePath, string sheetName)
        {
            try
            {
                using var doc = SpreadsheetDocument.Open(filePath, false);
                var workbookPart = doc.WorkbookPart;
                var wb = workbookPart?.Workbook;
                if (workbookPart == null || wb == null) return null;

                var sheet = wb.Descendants<OpenXmlSpreadsheet.Sheet>()
                    .FirstOrDefault(s => string.Equals(s.Name?.Value, sheetName, StringComparison.OrdinalIgnoreCase));
                if (sheet == null) return null;

                var wsPart = workbookPart.GetPartById(sheet.Id!) as WorksheetPart;
                var ws = wsPart?.Worksheet;
                if (ws == null) return null;

                var pm = ws.Descendants<OpenXmlSpreadsheet.PageMargins>().FirstOrDefault();
                var po = ws.Descendants<OpenXmlSpreadsheet.PrintOptions>().FirstOrDefault();
                var ps = ws.Descendants<OpenXmlSpreadsheet.PageSetup>().FirstOrDefault();

                var settings = new PageSettings();

                if (pm != null)
                {
                    // OOXML stores margins in inches → convert to points (×72)
                    if (pm.Left?.Value is not null) settings.LeftMargin = (double)pm.Left.Value * 72;
                    if (pm.Right?.Value is not null) settings.RightMargin = (double)pm.Right.Value * 72;
                    if (pm.Top?.Value is not null) settings.TopMargin = (double)pm.Top.Value * 72;
                    if (pm.Bottom?.Value is not null) settings.BottomMargin = (double)pm.Bottom.Value * 72;
                }

                if (po != null)
                {
                    if (po.HorizontalCentered?.Value is not null) settings.CenterHorizontally = po.HorizontalCentered.Value;
                    if (po.VerticalCentered?.Value is not null) settings.CenterVertically = po.VerticalCentered.Value;
                }

                if (ps?.Orientation?.Value is not null)
                {
                    settings.Orientation = ps.Orientation.Value.ToString().ToLower();
                }

                _logger.LogInformation(
                    "[OOXML] Read sheet '{Name}' PageSetup: LM={Lm} RM={Rm} TM={Tm} BM={Bm} CH={Ch} CV={Cv} O={O}",
                    sheetName, settings.LeftMargin, settings.RightMargin, settings.TopMargin, settings.BottomMargin,
                    settings.CenterHorizontally, settings.CenterVertically, settings.Orientation);

                return settings;
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "[OOXML] Failed to read sheet '{Name}' PageSetup from OOXML", sheetName);
                return null;
            }
        }

        // ────────────────────────────────────────────────────────────────────────
        // Comments Reader
        // ────────────────────────────────────────────────────────────────────────

        /// <summary>
        /// Read all cell comments from a worksheet via COM.
        /// Returns a list of (cellAddress, commentText).
        /// </summary>
        private List<(string address, string text)> ReadComments(Excel.Worksheet ws)
        {
            var result = new List<(string, string)>();

            try
            {
                dynamic? comments = null;
                try { comments = ws.Comments; } catch { }

                if (comments == null) return result;

                int commentCount = 0;
                try { commentCount = comments.Count; } catch { }

                for (int ci = 0; ci < commentCount; ci++)
                {
                    try
                    {
                        dynamic comment = comments[ci + 1];
                        dynamic parent = comment.Parent;

                        string address = "";
                        try { address = parent.Address; } catch { }

                        string text = "";
                        try { text = comment.Text() ?? ""; } catch { }

                        if (!string.IsNullOrWhiteSpace(address))
                        {
                            result.Add((address, text.Trim()));
                        }
                    }
                    catch
                    {
                        // Skip individual comment read failures
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to read comments from sheet '{Name}'", ws.Name);
            }

            return result;
        }

        // ────────────────────────────────────────────────────────────────────────
        // Page Settings Reader
        // ────────────────────────────────────────────────────────────────────────

        private PageSettings ReadPageSettings(Excel.Worksheet ws)
        {
            var settings = new PageSettings();

            try
            {
                var ps = ws.PageSetup;

                settings.Orientation = ps.Orientation == XlPageOrientation.xlLandscape
                    ? "landscape" : "portrait";
                // Use real Excel defaults as fallback (0.7in=50.4pt, 0.75in=54pt)
                // so MergeMargin can correctly identify these as "not explicitly set"
                settings.LeftMargin = SafeGetDouble(() => ps.LeftMargin, 50.4);
                settings.TopMargin = SafeGetDouble(() => ps.TopMargin, 54.0);
                settings.RightMargin = SafeGetDouble(() => ps.RightMargin, 50.4);
                settings.BottomMargin = SafeGetDouble(() => ps.BottomMargin, 54.0);

                try { settings.CenterHorizontally = (bool)ps.CenterHorizontally; } catch { }
                try { settings.CenterVertically = (bool)ps.CenterVertically; } catch { }

                int zoom = 0;
                try { zoom = (int)ps.Zoom; } catch { }
                if (zoom > 0) settings.Zoom = zoom;
                else settings.Zoom = 100;

                int fitW = 0, fitH = 0;
                try { fitW = (int)ps.FitToPagesWide; } catch { }
                try { fitH = (int)ps.FitToPagesTall; } catch { }
                settings.FitToPagesWide = fitW;
                settings.FitToPagesTall = fitH;

                // Paper size
                int paperSize = 0;
                try { paperSize = (int)ps.PaperSize; } catch { }
                settings.PaperSize = paperSize switch
                {
                    1 => "Letter",
                    5 => "Legal",
                    9 => "A4",
                    _ => $"Custom({paperSize})"
                };
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to read page settings");
            }

            return settings;
        }

        // ────────────────────────────────────────────────────────────────────────
        // Print Area Reader
        // ────────────────────────────────────────────────────────────────────────

        private PrintAreaInfo? ReadPrintArea(Excel.Worksheet ws)
        {
            try
            {
                string printArea = "";
                try { printArea = ws.PageSetup.PrintArea ?? ""; } catch { }

                if (string.IsNullOrWhiteSpace(printArea))
                    return null;

                return new PrintAreaInfo
                {
                    Address = printArea,
                    Cols = 0,
                    Rows = 0
                };
            }
            catch
            {
                return null;
            }
        }

        // ────────────────────────────────────────────────────────────────────────
        // Freeze Pane Reader
        // ────────────────────────────────────────────────────────────────────────

        private string? ReadFreezePane(Excel.Worksheet ws)
        {
            try
            {
                ws.Activate();
                bool hasFreezePanes = false;
                try { hasFreezePanes = (bool)ws.Application.ActiveWindow.FreezePanes; } catch { }

                if (hasFreezePanes)
                {
                    int scrollRow = 0, scrollCol = 0;
                    try { scrollRow = (int)ws.Application.ActiveWindow.ScrollRow; } catch { }
                    try { scrollCol = (int)ws.Application.ActiveWindow.ScrollColumn; } catch { }

                    if (scrollRow > 1 || scrollCol > 1)
                    {
                        return GetColumnLetter(scrollCol) + scrollRow;
                    }
                }
            }
            catch { }

            return null;
        }

        // ────────────────────────────────────────────────────────────────────────
        // Row Heights Reader
        // ────────────────────────────────────────────────────────────────────────

        private Dictionary<int, double> ReadRowHeights(Excel.Worksheet ws)
        {
            var result = new Dictionary<int, double>();

            try
            {
                var usedRange = ws.UsedRange;
                int lastRow = 0;
                try { lastRow = usedRange.Rows.Count + usedRange.Row - 1; } catch { return result; }

                for (int r = 1; r <= lastRow; r++)
                {
                    try
                    {
                        var row = (Excel.Range)ws.Rows[r];
                        double height = (double)row.RowHeight;
                        result[r] = height;
                        Marshal.ReleaseComObject(row);
                    }
                    catch { }
                }
            }
            catch { }

            return result;
        }

        // ────────────────────────────────────────────────────────────────────────
        // Column Widths Reader
        // ────────────────────────────────────────────────────────────────────────

        private Dictionary<int, double> ReadColumnWidths(Excel.Worksheet ws)
        {
            var result = new Dictionary<int, double>();

            try
            {
                var usedRange = ws.UsedRange;
                int lastCol = 0;
                try { lastCol = usedRange.Columns.Count + usedRange.Column - 1; } catch { return result; }

                for (int c = 1; c <= lastCol; c++)
                {
                    try
                    {
                        var col = (Excel.Range)ws.Columns[c];
                        double width = (double)col.ColumnWidth;
                        result[c] = width;
                        Marshal.ReleaseComObject(col);
                    }
                    catch { }
                }
            }
            catch { }

            return result;
        }

        // ────────────────────────────────────────────────────────────────────────
        // Merged Cells Reader
        // ────────────────────────────────────────────────────────────────────────

        private List<MergedCellInfo> ReadMergedCells(Excel.Worksheet ws)
        {
            var result = new List<MergedCellInfo>();

            try
            {
                // Iterate through UsedRange cells and check each cell's MergeArea
                // This avoids relying on Worksheet.MergeAreas which may not be exposed
                var usedRange = ws.UsedRange;
                if (usedRange == null) return result;

                int lastRow = usedRange.Row + usedRange.Rows.Count - 1;
                int lastCol = usedRange.Column + usedRange.Columns.Count - 1;

                Marshal.ReleaseComObject(usedRange);

                var visited = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

                int maxRow = Math.Min(lastRow, 500);
                int maxCol = Math.Min(lastCol, 100);

                for (int r = 1; r <= maxRow; r++)
                {
                    for (int c = 1; c <= maxCol; c++)
                    {
                        try
                        {
                            var cell = ws.Cells[r, c];
                            bool isMerged = false;
                            try { isMerged = (bool)cell.MergeCells; } catch { }

                            if (isMerged)
                            {
                                dynamic mergeArea = cell.MergeArea;
                                string address = "";
                                try { address = mergeArea.Address; } catch { }

                                if (!string.IsNullOrEmpty(address) && !visited.Contains(address))
                                {
                                    visited.Add(address);
                                    result.Add(new MergedCellInfo
                                    {
                                        Address = address,
                                        CellAddress = address.Split(':')[0]
                                    });
                                }
                            }

                            Marshal.ReleaseComObject(cell);
                        }
                        catch { }
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to read merged cells");
            }

            return result;
        }

        // ────────────────────────────────────────────────────────────────────────
        // Cell Styles Reader
        // ────────────────────────────────────────────────────────────────────────

        private Dictionary<string, CellStyleInfo> ReadCellStyles(Excel.Worksheet ws)
        {
            var result = new Dictionary<string, CellStyleInfo>();

            try
            {
                // Read styles from merged cells by iterating UsedRange and checking MergeCells
                var usedRange = ws.UsedRange;
                if (usedRange == null) return result;

                int lastRow = usedRange.Row + usedRange.Rows.Count - 1;
                int lastCol = usedRange.Column + usedRange.Columns.Count - 1;

                Marshal.ReleaseComObject(usedRange);

                var visitedAddrs = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

                int maxRow = Math.Min(lastRow, 500);
                int maxCol = Math.Min(lastCol, 100);

                for (int r = 1; r <= maxRow; r++)
                {
                    for (int c = 1; c <= maxCol; c++)
                    {
                        try
                        {
                            var cell = ws.Cells[r, c];
                            string cellAddr = "";

                            bool isMerged = false;
                            try { isMerged = (bool)cell.MergeCells; } catch { }

                            if (isMerged)
                            {
                                // For merged cells, use the top-left cell as the key
                                dynamic mergeArea = cell.MergeArea;
                                try { cellAddr = mergeArea.Address.Split(':')[0]; } catch { }
                            }
                            else
                            {
                                // For single cells, check if it has a comment (field indicator)
                                // cell.Comment returns a Comment object or null, not a bool
                                bool hasComment = false;
                                try { hasComment = cell.Comment != null; } catch { }
                                if (!hasComment) { Marshal.ReleaseComObject(cell); continue; }
                                try { cellAddr = cell.Address; } catch { }
                            }

                            if (!string.IsNullOrEmpty(cellAddr) && !visitedAddrs.Contains(cellAddr))
                            {
                                visitedAddrs.Add(cellAddr);
                                var range = ws.Range[cellAddr];
                                var style = ReadStyleFromRange(range);
                                result[cellAddr] = style;
                                Marshal.ReleaseComObject(range);
                            }

                            Marshal.ReleaseComObject(cell);
                        }
                        catch { }
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to read cell styles");
            }

            return result;
        }

        /// <summary>
        /// Read font, color, fill, alignment, and wrap from an Excel Range.
        /// </summary>
        private static CellStyleInfo ReadStyleFromRange(Excel.Range range)
        {
            var style = new CellStyleInfo();

            try { style.FontName = range.Font.Name; } catch { }
            try { style.FontSize = (double)range.Font.Size; } catch { }
            try { style.Bold = (bool)range.Font.Bold; } catch { }
            try { style.Italic = (bool)range.Font.Italic; } catch { }
            try { style.Underline = (bool)range.Font.Underline; } catch { }

            try
            {
                var fontColor = range.Font.Color;
                if (fontColor != null)
                {
                    int rgb = System.Convert.ToInt32(fontColor);
                    style.Color = $"#{rgb & 0xFFFFFF:X6}";
                }
            }
            catch { }

            try
            {
                var fillColor = range.Interior.Color;
                if (fillColor != null)
                {
                    int rgb = System.Convert.ToInt32(fillColor);
                    style.FillColor = $"#{rgb & 0xFFFFFF:X6}";
                }
            }
            catch { }

            try
            {
                int hAlign = (int)range.HorizontalAlignment;
                style.HorizontalAlignment = hAlign switch
                {
                    -4131 /* xlHAlignLeft */ => "left",
                    -4108 /* xlHAlignCenter */ => "center",
                    -4152 /* xlHAlignRight */ => "right",
                    _ => null
                };
            }
            catch { }

            try
            {
                int vAlign = (int)range.VerticalAlignment;
                style.VerticalAlignment = vAlign switch
                {
                    -4160 /* xlVAlignTop */ => "top",
                    -4108 /* xlVAlignCenter */ => "center",
                    -4107 /* xlVAlignBottom */ => "bottom",
                    _ => null
                };
            }
            catch { }

            try { style.WrapText = (bool)range.WrapText; } catch { }

            // Borders — capture individual edges from COM
            try { style.BorderLeft = ReadBorderCss(range, 7); } catch { }    // xlEdgeLeft
            try { style.BorderRight = ReadBorderCss(range, 10); } catch { }  // xlEdgeRight
            try { style.BorderTop = ReadBorderCss(range, 8); } catch { }     // xlEdgeTop
            try { style.BorderBottom = ReadBorderCss(range, 9); } catch { }  // xlEdgeBottom

            return style;
        }

        /// <summary>
        /// Read a single border edge from Excel COM and return CSS-style string
        /// like "1px solid #000000", or null if no border exists.
        /// </summary>
        private static string? ReadBorderCss(Excel.Range range, int edgeIndex)
        {
            try
            {
                var border = range.Borders[(XlBordersIndex)edgeIndex];
                object? lineStyleObj = null;
                try { lineStyleObj = border.LineStyle; } catch { }
                if (lineStyleObj == null) return null;

                int lineStyleVal = System.Convert.ToInt32(lineStyleObj);
                // xlLineStyleNone = -4142 means no border
                if (lineStyleVal == -4142) return null;

                string lineStyle = lineStyleVal switch
                {
                    -4115 => "dashed",   // xlDash
                    -4118 => "dotted",   // xlDot
                    -4119 => "double",   // xlDouble
                    _ => "solid"         // xlContinuous (-4142 already handled, but treat anything else as solid)
                };

                string width = "1px";
                try
                {
                    object? weightObj = border.Weight;
                    if (weightObj != null)
                    {
                        int wt = System.Convert.ToInt32(weightObj);
                        width = wt switch
                        {
                            -4138 => "2px", // xlMedium
                            4 => "3px",     // xlThick
                            _ => "1px"      // xlThin (2) or default
                        };
                    }
                }
                catch { }

                string colorStr = "#000000";
                try
                {
                    object? colorObj = border.Color;
                    if (colorObj != null)
                    {
                        int rgb = System.Convert.ToInt32(colorObj);
                        colorStr = $"#{rgb & 0xFFFFFF:X6}";
                    }
                }
                catch { }

                Marshal.ReleaseComObject(border);
                return $"{width} {lineStyle} {colorStr}";
            }
            catch
            {
                return null;
            }
        }

        // ────────────────────────────────────────────────────────────────────────
        // Cell Values Reader
        // ────────────────────────────────────────────────────────────────────────

        /// <summary>
        /// Read cell values from the worksheet for each field address.
        /// </summary>
        private Dictionary<string, string> ReadCellValues(
            Excel.Worksheet ws,
            List<(string address, string fieldId, string fieldName, string fieldType, string sheetName)> clustersFromFields,
            List<(string address, string text)>? comments)
        {
            var result = new Dictionary<string, string>();

            // Read values from _Fields addresses
            foreach (var (address, _, _, _, _) in clustersFromFields)
            {
                string cellAddr = address.Split(':')[0]; // Use first cell of merge range
                if (string.IsNullOrWhiteSpace(cellAddr)) continue;

                try
                {
                    var range = ws.Range[cellAddr];
                    object? value = null;
                    try { value = range.Value; } catch { }

                    if (value != null)
                    {
                        string strVal = value.ToString() ?? "";
                        if (!string.IsNullOrWhiteSpace(strVal))
                        {
                            result[cellAddr] = strVal;
                        }
                    }

                    Marshal.ReleaseComObject(range);
                }
                catch { }
            }

            // Also read values from comment addresses (fallback)
            if (comments != null)
            {
                foreach (var (addr, _) in comments)
                {
                    string cellAddr = addr.Split(':')[0];
                    if (result.ContainsKey(cellAddr)) continue;

                    try
                    {
                        var range = ws.Range[cellAddr];
                        object? value = null;
                        try { value = range.Value; } catch { }

                        if (value != null)
                        {
                            string strVal = value.ToString() ?? "";
                            if (!string.IsNullOrWhiteSpace(strVal))
                            {
                                result[cellAddr] = strVal;
                            }
                        }

                        Marshal.ReleaseComObject(range);
                    }
                    catch { }
                }
            }

            return result;
        }

        // ── Phase 3.4: Read as both FormDefinition and WorkbookDefinition ───

        /// <summary>
        /// Read an Output Excel workbook and return both FormDefinition (for existing
        /// consumers) and WorkbookDefinition (canonical model for future consumers).
        /// The WorkbookDefinition is built from the FormDefinition via the adapter.
        /// Returns null for both if the workbook cannot be read.
        /// </summary>
        public (FormDefinition? Form, WbDef.WorkbookDefinition? Definition) ReadAsDefinition(
            string filePath, string fileName)
        {
            var form = Read(filePath, fileName);
            if (form == null)
                return (null, null);

            try
            {
                var wbDef = WbDef.WorkbookDefinitionConverter.FromFormDefinition(form);
                wbDef.SourcePath = filePath;
                wbDef.SourceFileName = fileName;
                return (form, wbDef);
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to build WorkbookDefinition from FormDefinition — returning FormDefinition only");
                return (form, null);
            }
        }

        // ────────────────────────────────────────────────────────────────────────
        // Helpers
        // ────────────────────────────────────────────────────────────────────────

        private static string GetCellString(dynamic cell)
        {
            try
            {
                object? value = cell.Value;
                if (value == null) return "";
                return value.ToString()?.Trim() ?? "";
            }
            catch
            {
                return "";
            }
        }

        private static double SafeGetDouble(Func<object?> getter, double defaultValue)
        {
            try
            {
                object? val = getter();
                if (val == null) return defaultValue;
                return System.Convert.ToDouble(val);
            }
            catch
            {
                return defaultValue;
            }
        }

        /// <summary>
        /// Parse comment text in legacy ConMas format into InputParameters dictionary.
        /// Format: Name\nType\n\nParams or 0
        /// </summary>
        private static Dictionary<string, string> ParseCommentText(string text)
        {
            var result = new Dictionary<string, string>();
            if (string.IsNullOrWhiteSpace(text)) return result;

            string[] lines = text.Split('\n', StringSplitOptions.RemoveEmptyEntries);

            if (lines.Length >= 1)
                result["name"] = lines[0].Trim();
            if (lines.Length >= 2)
                result["type"] = lines[1].Trim();
            if (lines.Length >= 4)
            {
                string paramStr = lines[3].Trim();
                if (!string.IsNullOrEmpty(paramStr) && paramStr != "0")
                {
                    // Parse semicolon-delimited key=value pairs
                    foreach (var pair in paramStr.Split(';', StringSplitOptions.RemoveEmptyEntries))
                    {
                        int eqIdx = pair.IndexOf('=');
                        if (eqIdx > 0)
                        {
                            string key = pair[..eqIdx].Trim();
                            string val = pair[(eqIdx + 1)..].Trim();
                            if (!string.IsNullOrEmpty(key))
                                result[key] = val;
                        }
                    }
                }
            }

            return result;
        }

        /// <summary>
        /// Build a ClusterDefinition from _Fields sheet row data, enriched with comment metadata.
        /// </summary>
        private static ClusterDefinition? BuildClusterFromDefinition(
            FormDefinition form,
            string address, string fieldId, string fieldName, string fieldType, string sheetName,
            Dictionary<string, List<(string address, string text)>> commentsBySheet,
            int clusterIdx)
        {
            var targetSheet = form.Sheets.FirstOrDefault(s =>
                string.Equals(s.Name, sheetName, StringComparison.OrdinalIgnoreCase));
            string sid = targetSheet?.Id ?? "sheet_0";

            // Parse input parameters from comment text if available
            var inputParams = new Dictionary<string, string>();
            string commentText = "";

            if (targetSheet != null && commentsBySheet.TryGetValue(targetSheet.Name, out var sheetComments))
            {
                var cmt = sheetComments.FirstOrDefault(c =>
                    string.Equals(c.address, address.Split(':')[0], StringComparison.OrdinalIgnoreCase));
                if (cmt.text != "")
                {
                    commentText = cmt.text;
                    inputParams = ParseCommentText(cmt.text);
                }
            }

            var cluster = new ClusterDefinition
            {
                ClusterId = !string.IsNullOrEmpty(fieldId) ? fieldId : $"field_{clusterIdx}",
                Name = !string.IsNullOrEmpty(fieldName) ? fieldName : $"Field_{clusterIdx}",
                Type = !string.IsNullOrEmpty(fieldType) ? fieldType : "text",
                SheetId = sid,
                CellAddress = address,
                InputParameters = inputParams,
                Visibility = "visible",
                Readonly = false,
                Remarks = commentText,
                Functions = new List<string>(),
                Metadata = new Dictionary<string, string>
                {
                    ["isMerged"] = address.Contains(":") ? "true" : "false",
                    ["mergeAddress"] = address.Contains(":") ? address : "",
                    ["source"] = "_fields"
                }
            };

            // Read the current value from CellValues
            if (targetSheet != null)
            {
                targetSheet.CellValues.TryGetValue(address.Split(':')[0], out var currentValue);
                cluster.Metadata["currentValue"] = currentValue ?? "";
            }

            return cluster;
        }

        /// <summary>
        /// Convert a column number to a letter (1 = A, 2 = B, ... 27 = AA).
        /// </summary>
        private static string GetColumnLetter(int col)
        {
            string result = "";
            while (col > 0)
            {
                col--;
                result = (char)('A' + col % 26) + result;
                col /= 26;
            }
            return result;
        }

        // ────────────────────────────────────────────────────────────────────────
        // PageSetup Merge — legacy _Fields recovery
        // ────────────────────────────────────────────────────────────────────────

        /// <summary>
        /// Merge PageSettings from _Fields sheet into content sheet PageSettings.
        ///
        /// Legacy workbooks store authoritative PageSetup on the hidden _Fields sheet
        /// (centering, margins). The visible content sheet only has Excel defaults.
        /// This method fills those gaps without overwriting explicit content-sheet values.
        ///
        /// Merge rules per property:
        ///   Boolean (CenterHorizontally, CenterVertically):
        ///     content || fields  — if either is true, use true.
        ///     A content-sheet false is ambiguous (default vs explicit), so _Fields fills in.
        ///
        ///   Double (margins): use _Fields value when content is within tolerance of the
        ///     well-known Excel default margins (0.7 in left/right, 0.75 in top/bottom).
        ///     These Excel application defaults are stable across all modern Excel versions.
        ///     If content has a clearly non-default margin, keep it (content has priority).
        ///
        ///   String (Orientation): use _Fields when content's orientation equals the Excel
        ///     default ("portrait"). If content has been explicitly set to "landscape", keep it.
        ///
        ///   Zoom, FitToPagesWide, FitToPagesTall: use _Fields when content equals the
        ///     neutral value (100 for zoom, 0 for fit-to-page). Otherwise keep content.
        /// </summary>
        private PageSettings MergePageSettings(PageSettings content, PageSettings fields)
        {
            // ── Booleans ────────────────────────────────────────────────────────
            bool mergedCenterH = content.CenterHorizontally || fields.CenterHorizontally;
            bool mergedCenterV = content.CenterVertically || fields.CenterVertically;

            // ── Margins ─────────────────────────────────────────────────────────
            double mergedLeftMargin   = MergeMargin(content.LeftMargin,   fields.LeftMargin);
            double mergedRightMargin  = MergeMargin(content.RightMargin,  fields.RightMargin);
            double mergedTopMargin    = MergeMargin(content.TopMargin,    fields.TopMargin);
            double mergedBottomMargin = MergeMargin(content.BottomMargin, fields.BottomMargin);

            // ── Orientation ─────────────────────────────────────────────────────
            string mergedOrientation = MergeOrientation(content.Orientation, fields.Orientation);

            // ── Zoom & Fit ──────────────────────────────────────────────────────
            int mergedZoom          = MergeIntProperty(content.Zoom,          fields.Zoom,          100);
            int mergedFitToPagesW   = MergeIntProperty(content.FitToPagesWide, fields.FitToPagesWide, 0);
            int mergedFitToPagesT   = MergeIntProperty(content.FitToPagesTall, fields.FitToPagesTall, 0);

            // ── PaperSize ───────────────────────────────────────────────────────
            string mergedPaperSize = MergeStringProperty(content.PaperSize, fields.PaperSize, "Letter");

            // ── Log merge decisions ─────────────────────────────────────────────
            _logger.LogInformation(
                "[PAGESETUP-MERGE] Content H={Ch} V={Cv} LM={Lm} RM={Rm} TM={Tm} BM={Bm} O={O} Z={Z} FW={Fw} FH={Fh} PS={Ps}",
                content.CenterHorizontally, content.CenterVertically,
                content.LeftMargin, content.RightMargin, content.TopMargin, content.BottomMargin,
                content.Orientation, content.Zoom, content.FitToPagesWide, content.FitToPagesTall,
                content.PaperSize);
            _logger.LogInformation(
                "[PAGESETUP-MERGE] _Fields  H={Ch} V={Cv} LM={Lm} RM={Rm} TM={Tm} BM={Bm} O={O} Z={Z} FW={Fw} FH={Fh} PS={Ps}",
                fields.CenterHorizontally, fields.CenterVertically,
                fields.LeftMargin, fields.RightMargin, fields.TopMargin, fields.BottomMargin,
                fields.Orientation, fields.Zoom, fields.FitToPagesWide, fields.FitToPagesTall,
                fields.PaperSize);
            _logger.LogInformation(
                "[PAGESETUP-MERGE] Merged   H={Ch} V={Cv} LM={Lm} RM={Rm} TM={Tm} BM={Bm} O={O} Z={Z} FW={Fw} FH={Fh} PS={Ps}",
                mergedCenterH, mergedCenterV,
                mergedLeftMargin, mergedRightMargin, mergedTopMargin, mergedBottomMargin,
                mergedOrientation, mergedZoom, mergedFitToPagesW, mergedFitToPagesT,
                mergedPaperSize);

            return new PageSettings
            {
                CenterHorizontally = mergedCenterH,
                CenterVertically   = mergedCenterV,
                LeftMargin         = mergedLeftMargin,
                RightMargin        = mergedRightMargin,
                TopMargin          = mergedTopMargin,
                BottomMargin       = mergedBottomMargin,
                Orientation        = mergedOrientation,
                Zoom               = mergedZoom,
                FitToPagesWide     = mergedFitToPagesW,
                FitToPagesTall     = mergedFitToPagesT,
                PaperSize          = mergedPaperSize,
            };
        }

        /// <summary>
        /// Merge a left/right margin value. Excel default is 50.4 pt (0.7 in).
        /// If content is within 0.5 pt of the Excel default, treat it as unset
        /// and fall back to _Fields. Otherwise keep the content value.
        /// </summary>
        private static double MergeMargin(double content, double fields)
        {
            const double excelDefaultLeftRight = 50.4; // 0.7 inches in points
            const double excelDefaultTopBottom = 54.0; // 0.75 inches in points
            // Tight tolerance — COM sometimes rounds 53.858pt → 54pt but the real
            // value is still custom, not the Excel default of exactly 54.0.
            // Any margin that differs from the exact default by more than 0.05pt
            // is treated as an explicit non-default value and kept.
            const double tolerance = 0.05;

            bool contentIsDefault =
                Math.Abs(content - excelDefaultLeftRight) < tolerance ||
                Math.Abs(content - excelDefaultTopBottom) < tolerance;

            return contentIsDefault ? fields : content;
        }

        /// <summary>
        /// Merge Orientation. Excel default is "portrait".
        /// If content is "portrait", it may be the default → use _Fields.
        /// If content is "landscape", it was explicitly set → keep it.
        /// </summary>
        private static string MergeOrientation(string content, string fields)
        {
            if (string.Equals(content, "landscape", StringComparison.OrdinalIgnoreCase))
                return content;
            return fields;
        }

        /// <summary>
        /// Merge an integer PageSetup property (Zoom, FitToPagesWide, FitToPagesTall).
        /// If content equals the neutral value, use _Fields. Otherwise keep content.
        /// </summary>
        private static int MergeIntProperty(int content, int fields, int neutralValue)
        {
            return content == neutralValue ? fields : content;
        }

        /// <summary>
        /// Merge a string PageSetup property (PaperSize).
        /// If content equals the neutral value, use _Fields. Otherwise keep content.
        /// </summary>
        private static string MergeStringProperty(string content, string fields, string neutralValue)
        {
            if (string.Equals(content, neutralValue, StringComparison.OrdinalIgnoreCase))
                return fields;
            return content;
        }

        // ════════════════════════════════════════════════════════════════════════
        // PHASE X.28 — TEMPORARY DIAGNOSTIC: LogPageSetup helper
        // ════════════════════════════════════════════════════════════════════════
        private void LogPageSetup(string label, Excel.Worksheet ws)
        {
            try
            {
                var ps = ws.PageSetup;
                string printArea = "";
                try { printArea = ps.PrintArea ?? ""; } catch { printArea = "ERR"; }
                string centerH = "ERR", centerV = "ERR";
                try { centerH = ((bool)ps.CenterHorizontally).ToString(); } catch { }
                try { centerV = ((bool)ps.CenterVertically).ToString(); } catch { }
                double lm = -1, rm = -1, tm = -1, bm = -1, hm = -1, fm = -1;
                try { lm = (double)ps.LeftMargin; } catch { }
                try { rm = (double)ps.RightMargin; } catch { }
                try { tm = (double)ps.TopMargin; } catch { }
                try { bm = (double)ps.BottomMargin; } catch { }
                try { hm = (double)ps.HeaderMargin; } catch { }
                try { fm = (double)ps.FooterMargin; } catch { }
                string orient = "ERR";
                try { orient = ps.Orientation == XlPageOrientation.xlLandscape ? "landscape" : "portrait"; } catch { }
                int paperSize = -1, zoom = -1, fitW = -1, fitH = -1;
                try { paperSize = (int)ps.PaperSize; } catch { }
                try { zoom = (int)ps.Zoom; } catch { }
                try { fitW = (int)ps.FitToPagesWide; } catch { }
                try { fitH = (int)ps.FitToPagesTall; } catch { }

                _logger.LogInformation(
                    "[X28] [{Label}] COM: PA=[{PA}] CH={CH} CV={CV} " +
                    "LM={LM:F4} RM={RM:F4} TM={TM:F4} BM={BM:F4} HM={HM:F4} FM={FM:F4} " +
                    "O={O} PS={PS} Z={Z} FW={FW} FH={FH}",
                    label,
                    printArea, centerH, centerV,
                    lm, rm, tm, bm, hm, fm,
                    orient, paperSize, zoom, fitW, fitH);
            }
            catch (Exception ex)
            {
                _logger.LogWarning("[X28] [{Label}] LogPageSetup FAILED: {Msg}", label, ex.Message);
            }
        }
    }
}
